### ISSUE TITLE
U5 has no +5V power connected to pin 20

### ISSUE THREAD

**Issue by pi1541** [soniccd123/SNES-FeRAM-Cart#1]
Have you tried your Kicad PCB?
U5 has no +5 power connected to pin 20.
Perhaps the CMOS just works?

**Comment by soniccd123** [comment]
Hey, sorry, just seen this now. It is already fixed, I forgot this trace somehow when I changed the EPROM from the front to the backside of the PCB (to fit the case correctly). Thanks for pointing out.
