### ISSUE TITLE
Does this design work?

### ISSUE THREAD

**Issue by pi1541** [soniccd123/SNES-FeRAM-Cart#3]
Hi.
I have made a number of these but I can't get any of them to work.
I am trying V3.1.
I am trying many HiROM images and have all the jumpers set to H.
I have all the dip switches turned on.

I have a wire jumper from pin 1 to pin 20 of U5 to fix the missing 5v connection to pin 20 of U5. Is this correct?
Can I confirm that the silk screen for U1, U2 and U7 is the wrong way around and all of these chips have their pin 1 closest to the left side of the board where the dip switches are? That is opposite to the U labels on the silk screen.
Are any other markings on the silk screen wrong?

When you say "byte swapped" do you mean byte swapped using a tool like Wasabi or do you mean 16bit endian byte swapped? I have tried both and neither worked.

I know that my CIC chip works as it works successfully in other designs.

I don't know what to try next. All attempt give a black screen.

I have built other peoples designs without issue but can't seem get this one to work.
Any help or advice would be greatly appreciated.
I want to use this design as it has many desirable features and looks like it is the best one yet.

Oh, and another little thing. In the README.dm in the paragraph about bank switching it talks about the Sega Genesis and not the SNES.

Thanks.

**Comment by soniccd123** [comment]
Hello!

Yes, the design work, me and a bunch of other users at NesDev forums have tested it and made repros successfully.

The wire from pin 1 to 20 on U5 is correct and works. Also, I can confirm that U1, U2 and U7 have indeed pin 1 in direction of the DIP switches. Thanks for pointing out, may change the silkscreen in next commit.

Be aware that U5 and U6 are both in oposite directions from each other, in this case, U5 pin 1 is in direction of the back side jumpers. 

To see the correct orientation of the chips in KiCAD, take a look at the F.Fab and B.Fab layers, they show the pin 1 of each chip explicitly. KiCAD's silkscreen markings are terrible, in the next commit, I will add very explicit marks for pin 1 of each chip, as this is causing problems even to me lol.

With byteswapped I mean that odd and even bytes must be swapped, if bytes 0, 1, 2 and 3 in the file are A, B, C and D you must write them in the EPROM as B, A, D, C. Each word must be swapped, so it is 16bit endianness, not the Wasabi swap (that changes addresses to fit diferent EPROMs pinouts).

Thanks for pointing out about the Genesis mistake, I use the exact same bank switching method in this and my Genesis Repro, so must have forgot to change the names lol.

Hope this helps!

**Comment by pi1541** [comment]
Thanks, I will keep debugging my soldering work.

**Comment by pi1541** [comment]
I tried it on another SNES and it worked perfectly. Thanks.
